
###
@HOSTAPI=http://127.0.0.1:3333


POST {{HOSTAPI}}/groups/ HTTP/1.1
Content-Type: application/json

{ 
  "name_group":"TESTE",
  "description": "Esse grupo foi criado para TESTE",
  "color_hex": "#000",
  "user_id":"2ffbc5e8-230a-4f66-a3a5-b3e37520e893"
}

#####
DELETE  {{HOSTAPI}}/groups/c5cda5cf-bd31-4014-a583-e4ce31f35a43 HTTP/1.1

 
### 

GET {{HOSTAPI}}/groups/ HTTP/1.1
Content-Type: application/json
 
### 


### 

POST {{HOSTAPI}}/groups/filter HTTP/1.1
Content-Type: application/json

{
  "filter":"%%"
}
 
### 




GET {{HOSTAPI}}/users/mateus1@gmail.com HTTP/1.1
Content-Type: application/json
 


### 


#####
GET {{HOSTAPI}}/groups/f20f9d55-ed82-4d5f-998d-488e9694afc2 HTTP/1.1
Content-Type: application/json
 
###


PUT {{HOSTAPI}}/groups/update/c3da0b30-9fae-40ba-ab2b-564ef09800eb HTTP/1.1
Content-Type: application/json

{ 
  "name_group":"teste 2.0",
  "description": "Grupo 1 responsavel XXXXX",
  "color_hex": "#000",
  "user_id":"4618e8c2-ee25-4257-bb6a-91310238bfd3"
}
###