
###
@HOSTAPI=http://127.0.0.1:3333


POST {{HOSTAPI}}/userpost/ HTTP/1.1
Content-Type: application/json

{
  "userId":"4231f81d-7799-42fd-b5ce-b61c11922ec7",
  "postId":"e18f345d-7dd1-4f66-988a-bee2c95ad8d8"
}

#####
DELETE  {{HOSTAPI}}/groups/1e79b847-2e48-410d-9b16-2bdaea0729ca HTTP/1.1

 
### 

GET {{HOSTAPI}}/postsgroups/Ppage=1&pPer_page=10 HTTP/1.1
Content-Type: application/json
 
### 





GET {{HOSTAPI}}/users/mateus1@gmail.com HTTP/1.1
Content-Type: application/json
 


### 
