
###
@HOSTAPI=http://127.0.0.1:3333


POST {{HOSTAPI}}/postsgroups/ HTTP/1.1
Content-Type: application/json

{
  "groupId":"31f153f9-9f8a-47b7-a877-04462dab0152",
  "postId":"e18f345d-7dd1-4f66-988a-bee2c95ad8d8"
}

#####
DELETE  {{HOSTAPI}}/groups/1e79b847-2e48-410d-9b16-2bdaea0729ca HTTP/1.1

 
### 

GET {{HOSTAPI}}/postsgroups/Ppage=1&pPer_page=10 HTTP/1.1
Content-Type: application/json
 
### 





GET {{HOSTAPI}}/users/mateus1@gmail.com HTTP/1.1
Content-Type: application/json
 


### 
